---
clickhouse:
  hosts:
    clickhouse1:
      ansible_host: 51.250.12.227
      ansible_user: centos

lighthouse:
  hosts:
    lighthouse1:
      ansible_host: 158.160.33.39
      ansible_user: centos

vector:
  hosts:
    vector1:
      ansible_host: 84.201.131.143
      ansible_user: centos

